import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ShieldCheck } from 'lucide-react';
import { Button } from '@/shared/components/Button';
import { Input } from '@/shared/components/Input';
import { Select } from '@/shared/components/Select';
import { FormField } from '@/shared/components/FormField';
import { ROUTES } from '@/config/constants';
import {
  companyProfileSchema,
  COMPANY_PROFILE_FIELDS,
  type CompanyProfile,
} from '../questions/companyProfile';

/**
 * Captures the Company Profile before the assessment questions (PRD
 * Section 4 — a partial drop-off still yields a contactable lead).
 * The form has no hardcoded fields — it's generated by mapping over
 * COMPANY_PROFILE_FIELDS (features/assessment/companyProfile.ts), so
 * changing what's collected means editing that list, not this file.
 *
 * Purely client-side for now: no submission endpoint exists yet, so
 * "Begin Assessment" just carries the validated profile forward via
 * router state, stored separately from question answers (which are
 * collected next, in AssessmentQuestionsView).
 */
export function CompanyInfoForm() {
  const navigate = useNavigate();
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<CompanyProfile>({
    resolver: zodResolver(companyProfileSchema),
  });

  const businessType = watch('businessType');

  const onSubmit = (values: CompanyProfile) => {
    navigate(ROUTES.assessmentQuestions, { state: values });
  };

  return (
    <motion.form
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.1 }}
      onSubmit={handleSubmit(onSubmit)}
      className="mt-10 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"
    >
      <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
        {COMPANY_PROFILE_FIELDS.map((field) => {
          const fieldError = errors[field.name]?.message;

          return (
            <FormField key={field.name} label={field.label} htmlFor={field.name} error={fieldError}>
              {field.type === 'select' ? (
                <Select id={field.name} hasError={!!fieldError} defaultValue="" {...register(field.name)}>
                  <option value="" disabled>
                    Select {field.label.toLowerCase()}
                  </option>
                  {field.options?.map((option) => (
                    <option key={option} value={option}>
                      {option}
                    </option>
                  ))}
                </Select>
              ) : (
                <Input
                  id={field.name}
                  type={field.type}
                  placeholder={field.placeholder}
                  hasError={!!fieldError}
                  {...register(field.name)}
                />
              )}

              {field.name === 'businessType' && businessType === 'Other' ? (
                <Input
                  id="businessTypeOther"
                  placeholder="Describe your business type"
                  hasError={!!errors.businessTypeOther}
                  className="mt-2"
                  {...register('businessTypeOther')}
                />
              ) : null}
            </FormField>
          );
        })}
      </div>

      <Button type="submit" variant="primary" size="lg" className="mt-8 w-full" disabled={isSubmitting}>
        Begin Assessment
        <ArrowRight className="h-4 w-4" />
      </Button>

      <p className="mt-4 flex items-center justify-center gap-1.5 text-xs text-slate-500">
        <ShieldCheck className="h-3.5 w-3.5 text-brand" />
        Your information is 100% confidential and used only to prepare your report.
      </p>
    </motion.form>
  );
}
